# Generated by Django 3.1.7 on 2022-04-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=2, max_digits=12)),
                ('y', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='backend_diploma.position')),
            ],
        ),
    ]
